### ISSUE TITLE
Using /etc/slint-version

### ISSUE THREAD

**Issue by gapan** [DidierSpaier/eliloconfig#1]
I noticed you are using `/etc/slint-version` in eliloconfig. I'm guessing this is a result of a sed command. Unless you're going to include such a file, I think you probably meant `/etc/slackware-version`.

**Comment by DidierSpaier** [comment]
On 21/04/2016 13:33, George Vlahavas wrote:> I noticed you are using `/etc/slint-version` in eliloconfig. I'm guessing this is a result of a sed command. Unless you're going to include such a file, I think you probably meant `/etc/slackware-version`.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/DidierSpaier/eliloconfig/issues/1

Well, I consider including this file. One of the reasons is I do not
rule out the idea of providing "intermediate version" tha woukd not
change the base system but maybe include new or updated translations.
Say, version 14.2.1, 14.2.2, etc. 

This would be mostly useful for translations or modifications of the
installer, as else just updating a few packages would suffice still
providing the same ISO.

I am not sure to be aware of all the potential consequences, though.
Do you have any clue about that?

**Comment by gapan** [comment]
Sorry for the late reply...

No, there should be no problem with including such a file. Since you are doing it already, I'll close this.
